name: deep-learning
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - aom=3.12.1
  - attrs=25.4.0
  - blas=1.0
  - blosc=1.21.6
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - geos=3.10.6
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - imageio=2.37.2
  - jansson=2.14
  - jinja2=3.1.6
  - jpeg=9f
  - json-c=0.18
  - kiwisolver=1.4.9
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.11.4
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libiconv=1.16
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - libkml=1.3.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libunistring=1.3
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - minizip=4.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - proj=9.3.1
  - pycparser=2.23
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - qhull=2020.2
  - rasterio=1.4.4
  - readline=8.3
  - requests=2.32.5
  - scikit-image=0.25.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tifffile=2025.10.4
  - tk=8.6.15
  - torchvision=0.20.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uriparser=0.9.8
  - urllib3=2.6.1
  - wheel=0.45.1
  - xerces-c=3.3.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
