name: deep-learning
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aom=3.9.1
  - attrs=25.4.0
  - blosc=1.21.6
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.22.0
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charls=2.4.2
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cpython=3.13.11
  - dav1d=1.2.1
  - filelock=3.20.0
  - fmt=12.0.0
  - freexl=2.0.0
  - fsspec=2025.12.0
  - geos=3.14.1
  - geotiff=1.7.4
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=75.1
  - imagecodecs=2025.11.11
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - json-c=0.18
  - jxrlib=1.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.2
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.10.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libuuid=2.41.2
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=21.1.7
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.3
  - minizip=4.0.10
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.6
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.18.0
  - packaging=25.0
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - proj=9.7.1
  - pthread-stubs=0.4
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pyparsing=3.2.5
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pytorch=2.9.1
  - pywavelets=1.9.0
  - rasterio=1.4.3
  - rav1e=0.7.1
  - readline=8.2
  - scikit-image=0.25.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.1
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tifffile=2025.10.16
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uriparser=0.9.8
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
prefix: /home/iaquobe/.conda/envs/deep-learning
