name: deep-learning
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=he440d0b_1
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.22.0=hc31b594_1
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charls=2.4.2=h59595ed_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cpython=3.13.11=py313hd8ed1ab_100
  - dav1d=1.2.1=hd590300_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fmt=12.0.0=h2b0788b_0
  - freexl=2.0.0=h9dce30a_2
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - geos=3.14.1=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - icu=75.1=he02047a_0
  - imagecodecs=2025.11.11=py313hf092b87_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json-c=0.18=h6688a6e_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=4_h5875eb1_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=4_hfef963f_mkl
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgdal-core=3.10.3=h1f481a6_27
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=4_h5e43f62_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_2
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.1=hee844dc_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.9.1=cpu_mkl_hf3ca1bf_101
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=he1b5a44_0
  - llvm-openmp=21.1.7=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.3=py313h3dea7bd_0
  - minizip=4.0.10=h05a5f5f_0
  - mkl=2025.3.0=h0e700b2_462
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6=pyhcf101f3_0
  - numpy=2.3.5=py313hf6604e3_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py313h7037e92_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py313h80991f8_2
  - pip=25.3=pyh145f28c_0
  - proj=9.7.1=h99ae125_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=3.0.1=pyh97977ab_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.13.11=hc97d973_100_cp313
  - python_abi=3.13=8_cp313
  - pytorch=2.9.1=cpu_mkl_py313_h5a1586b_101
  - pywavelets=1.9.0=py313h29aa505_2
  - rasterio=1.4.3=py313h6bd603e_3
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - scikit-image=0.25.2=py313h08cd8bf_2
  - scipy=1.16.3=py313h11c21cd_1
  - setuptools=80.9.0=pyhff2d567_0
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=heff268d_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_1
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uriparser=0.9.8=hac33072_0
  - xerces-c=3.3.0=h988505b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/iaquobe/.conda/envs/deep-learning
